# Laptop Monitor Profile (Laptop only)

# Internal Laptop Screen
monitor = desc:BOE 0x091B, 1920x1080@60, 0x0, 1

# Bind Workspaces 1-10 to the Laptop screen
workspace = 1, monitor:desc:BOE 0x091B, default:true
workspace = 2, monitor:desc:BOE 0x091B
workspace = 3, monitor:desc:BOE 0x091B
workspace = 4, monitor:desc:BOE 0x091B
workspace = 5, monitor:desc:BOE 0x091B
workspace = 6, monitor:desc:BOE 0x091B
workspace = 7, monitor:desc:BOE 0x091B
workspace = 8, monitor:desc:BOE 0x091B
workspace = 9, monitor:desc:BOE 0x091B
workspace = 10, monitor:desc:BOE 0x091B
