# Window configuration

input {
    kb_layout = us

    device:alpsps/2-alps-dualpoint-stick {
        # Add your device-specific settings here
    }

    follow_mouse = 1
    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
}

general {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    gaps_in = 1
    gaps_out = 0
    border_size = 2
# gruvbox green 
#    col.active_border = rgba(b8bb26ff) rgba(8ec07cff) 45deg
#    col.inactive_border = rgba(595959aa)
# gruvbox purple
#    col.active_border = rgba(d3869bff) rgba(b16286ff) 45deg
#    col.inactive_border = rgba(595959aa)
# gruvbox green -purple 
    col.active_border = rgba(8ec07cff) rgba(b16286ff) 90deg
    col.inactive_border = rgba(595959aa)
#    col.active_border = rgba(99ccffee) rgba(00ff99ee) 45deg
#    col.inactive_border = rgba(595959aa)
    #col.active_border = rgba(595959aa)  # grey like your inactive border
    #col.inactive_border = rgba(00000000)  # fully transparent
    resize_on_border = true  # new feature

    layout = dwindle

    # Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
    allow_tearing = false
}
