#!/usr/bin/env bash

# Directory of monitor profiles
PROFILES_DIR="$HOME/.config/hypr/hyprland/profiles"
MONITORS_CONF="$HOME/.config/hypr/hyprland/monitors.conf"
HYPRPAPER_CONF="$HOME/.config/hypr/hyprpaper.conf"
WALLPAPERS_DIR="$HOME/.config/hypr/wallpapers"

# Function to generate dynamic hyprpaper.conf with random wallpapers for a profile
randomize_wallpapers() {
    local profile_path="$1"
    if [ ! -f "$profile_path" ]; then
        return 1
    fi

    # Find active monitors in the profile (exclude disabled ones)
    mapfile -t monitors < <(grep '^monitor[[:space:]]*=' "$profile_path" | grep -v 'disable' | cut -d'=' -f2- | cut -d',' -f1 | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')

    if [ ${#monitors[@]} -eq 0 ]; then
        return 0
    fi

    # Find all image files in the wallpapers directory (jpg, jpeg, png)
    local images=()
    while IFS= read -r -d '' file; do
        images+=("$file")
    done < <(find "$WALLPAPERS_DIR" -maxdepth 1 -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" \) -print0)

    if [ ${#images[@]} -eq 0 ]; then
        if command -v notify-send >/dev/null 2>&1; then
            notify-send "Wallpaper Randomizer" "No wallpapers found in $WALLPAPERS_DIR" -u critical
        fi
        return 1
    fi

    # Randomly assign a wallpaper to each active monitor
    declare -A preloads
    declare -A monitor_wallpapers

    for monitor in "${monitors[@]}"; do
        local rand_idx=$(( RANDOM % ${#images[@]} ))
        local selected_img="${images[$rand_idx]}"
        monitor_wallpapers["$monitor"]="$selected_img"
        preloads["$selected_img"]=1
    done

    # Remove symlink if exists to avoid overwriting profile templates
    rm -f "$HYPRPAPER_CONF"

    # Generate fresh hyprpaper.conf
    {
        echo "# Dynamically generated by switch_monitors.sh"
        echo "# Active layout profile: $(basename "$profile_path")"
        echo ""
        
        # Write preloads
        for img in "${!preloads[@]}"; do
            echo "preload = $img"
        done
        echo ""

        # Write monitor wallpaper blocks
        for monitor in "${!monitor_wallpapers[@]}"; do
            echo "wallpaper {"
            echo "    monitor = $monitor"
            echo "    path = ${monitor_wallpapers[$monitor]}"
            echo "    fit_mode = fill"
            echo "}"
        done
        echo ""
        echo "splash = false"
        echo "ipc = on"
    } > "$HYPRPAPER_CONF"

    # Restart hyprpaper to apply new wallpapers
    pkill hyprpaper
    sleep 0.2
    hyprpaper >/dev/null 2>&1 &
}

# --- Main Logic ---

# Check if we just want to randomize the current profile (e.g. on boot)
if [ "$1" = "--randomize" ]; then
    # Detect the active profile from the monitors.conf symlink
    if [ -L "$MONITORS_CONF" ]; then
        ACTIVE_PROFILE=$(readlink -f "$MONITORS_CONF")
        if [ -f "$ACTIVE_PROFILE" ]; then
            randomize_wallpapers "$ACTIVE_PROFILE"
            exit 0
        fi
    fi
    exit 1
fi

# Otherwise, run Rofi menu
OPTIONS="Laptop\nHome\nOffice\nPi_screen"
SELECTED=$(echo -e "$OPTIONS" | rofi -dmenu -p "Select Monitor Layout" -i)

if [ -z "$SELECTED" ]; then
    exit 0
fi

PROFILE_FILE=$(echo "$SELECTED" | tr '[:upper:]' '[:lower:]').conf
PROFILE_PATH="$PROFILES_DIR/$PROFILE_FILE"

if [ -f "$PROFILE_PATH" ]; then
    # Symlink the display layout
    ln -sf "$PROFILE_PATH" "$MONITORS_CONF"
    
    # Reload Hyprland
    hyprctl reload
    
    # Randomize and set wallpapers for this layout
    randomize_wallpapers "$PROFILE_PATH"
    
    # Notification
    if command -v notify-send >/dev/null 2>&1; then
        notify-send "Monitor Switcher" "Switched to '$SELECTED' layout with random wallpapers" -i video-display -t 2000
    fi
else
    if command -v notify-send >/dev/null 2>&1; then
        notify-send "Monitor Switcher" "Error: Profile file '$PROFILE_FILE' not found!" -u critical -i dialog-error
    fi
fi
